[package]
name = "pmr_test"
version = "0.1.0"
edition = "2024"

[dependencies]
rmp-serde = "1.3.0"
serde = { version = "1.0.219", features = ["derive"] }
pmr = { path = "../poor-mans-rpc" }
memory-module = { path = "../memory-module" }
rand = "0.9.0"
