[package]
name = "manifest-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = { version = "2.9.0", features = ["serde"] }
prost = "0.13.5"
prost-types = "0.13.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
