// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModuleFunctionArg {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(bool, optional, tag="3")]
    pub required: ::core::option::Option<bool>,
    #[prost(string, optional, tag="4")]
    pub help: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModuleFunction {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="3")]
    pub args: ::prost::alloc::vec::Vec<ModuleFunctionArg>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModuleDescriptor {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="3")]
    pub functions: ::prost::alloc::vec::Vec<ModuleFunction>,
}
// @@protoc_insertion_point(module)
