package whisper:module@1.0.0;

world whisper-module {
    record msg {
        module-id: string,
        command-id: u64,
        tx-id: u64,
        data: option<list<u8>>,
    }

    record module-func-arg {
        name: string,
        %type: string,
        required: bool,
        help: option<string>,
    }

    record module-func {
        name: string,
        description: option<string>,
        args: option<list<module-func-arg>>,
    }

    record module-descriptor {
        name: string,
        description: option<string>,
        funcs: option<list<module-func>>,
    }

    import message-out: func(msg: msg);

    export message-in: func(tx-id: u64, msg: list<u8>) -> result<_, u32>;

    export get-module-descriptor: func() -> module-descriptor;

    export get-module-data: func() -> list<u8>;

    export handle-command: func(tx-id: u64, command: string, args: list<string>);
}