// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Upload {
    #[prost(oneof="upload::Message", tags="1, 2")]
    pub message: ::core::option::Option<upload::Message>,
}
/// Nested message and enum types in `Upload`.
pub mod upload {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Request {
        #[prost(oneof="request::Message", tags="1, 2, 3")]
        pub message: ::core::option::Option<request::Message>,
    }
    /// Nested message and enum types in `Request`.
    pub mod request {
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Begin {
            #[prost(uint64, tag="1")]
            pub tx_id: u64,
            #[prost(string, tag="2")]
            pub dest: ::prost::alloc::string::String,
            #[prost(bytes="vec", tag="3")]
            pub chunk: ::prost::alloc::vec::Vec<u8>,
        }
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Chunk {
            #[prost(uint64, tag="1")]
            pub tx_id: u64,
            #[prost(uint64, tag="2")]
            pub seq_no: u64,
            #[prost(uint64, tag="3")]
            pub total: u64,
            #[prost(bytes="vec", tag="4")]
            pub chunk: ::prost::alloc::vec::Vec<u8>,
        }
        #[derive(Clone, Copy, PartialEq, ::prost::Message)]
        pub struct End {
            #[prost(uint64, tag="1")]
            pub tx_id: u64,
        }
        #[derive(Clone, PartialEq, ::prost::Oneof)]
        pub enum Message {
            #[prost(message, tag="1")]
            Begin(Begin),
            #[prost(message, tag="2")]
            Chunk(Chunk),
            #[prost(message, tag="3")]
            End(End),
        }
    }
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct Response {
        #[prost(oneof="response::Message", tags="1, 2, 3")]
        pub message: ::core::option::Option<response::Message>,
    }
    /// Nested message and enum types in `Response`.
    pub mod response {
        #[derive(Clone, Copy, PartialEq, ::prost::Message)]
        pub struct Begin {
            #[prost(uint64, tag="1")]
            pub tx_id: u64,
            #[prost(uint64, tag="2")]
            pub error: u64,
        }
        #[derive(Clone, Copy, PartialEq, ::prost::Message)]
        pub struct Chunk {
            #[prost(uint64, tag="1")]
            pub tx_id: u64,
            #[prost(uint64, tag="2")]
            pub seq_no: u64,
            #[prost(uint64, tag="3")]
            pub error: u64,
        }
        #[derive(Clone, Copy, PartialEq, ::prost::Message)]
        pub struct End {
            #[prost(uint64, tag="1")]
            pub tx_id: u64,
            #[prost(uint64, tag="2")]
            pub error: u64,
        }
        #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
        pub enum Message {
            #[prost(message, tag="1")]
            Begin(Begin),
            #[prost(message, tag="2")]
            Chunk(Chunk),
            #[prost(message, tag="3")]
            End(End),
        }
    }
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag="1")]
        Request(Request),
        #[prost(message, tag="2")]
        Response(Response),
    }
}
// @@protoc_insertion_point(module)
