// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct File {
    #[prost(oneof="file::Message", tags="1")]
    pub message: ::core::option::Option<file::Message>,
}
/// Nested message and enum types in `File`.
pub mod file {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag="1")]
        Upload(super::upload::Upload),
    }
}
// @@protoc_insertion_point(module)
